# ert tests

name: ert
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
    - name: Checkout units-mode
      uses: actions/checkout@v2
      with:
        repository: atreyagaurav/units-mode
        path: units-mode
    - name: Run Tests
      run: emacs -batch -l ./units-mode/units-mode.el -l ./litex-mode.el -l ert -l ./tests/litex-mode-tests.el -f ert-run-tests-batch-and-exit
